"""add_checkpoint_snapshots

Revision ID: 6d56e538d03e
Revises: None
Create Date: 2026-09-04 22:21:08.947379

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d56e538d03e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoint_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('avg_volume_20d', sa.Float(), nullable=True),
    sa.Column('volatility_20d', sa.Float(), nullable=True),
    sa.Column('market_return', sa.Float(), nullable=True),
    sa.Column('attention_score', sa.Float(), nullable=True),
    sa.Column('snapshot_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['user_checkpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkpoint_id', 'symbol', name='uq_checkpoint_symbol')
    )
    op.create_index(op.f('ix_checkpoint_snapshots_checkpoint_id'), 'checkpoint_snapshots', ['checkpoint_id'], unique=False)
    op.create_index(op.f('ix_checkpoint_snapshots_symbol'), 'checkpoint_snapshots', ['symbol'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkpoint_snapshots_symbol'), table_name='checkpoint_snapshots')
    op.drop_index(op.f('ix_checkpoint_snapshots_checkpoint_id'), table_name='checkpoint_snapshots')
    op.drop_table('checkpoint_snapshots')
    # ### end Alembic commands ###
